### ISSUE TITLE
Can't install this bundle in Symfony 4.2 or 4.3

### ISSUE THREAD

**Issue by SulivanDotEu** [Happyr/GoogleAnalyticsBundle#34]
Hi there !

We are very interested in using this bundle for our [project ](https://www.sport-finder.com) but we couldn't achieve to install it and make it work.

So we tried to reproduce our error in a brand new project.
Here are the step we followed:

- `symfony new httpclient`
- `composer require symfony/maker-bundle`
- `composer require template`
- ``
- `composer require happyr/google-analytics-bundle`
- ``
- ``
- ``

https://github.com/SulivanDotEu/GoogleAnalyticsBundleTest/tree/master

**Comment by jon-ht** [comment]
Hi @SulivanDotEu 

I encountered the same problem as you and tested most of your installs. In the end, here is what I've done to fix it :

1. `composer require symfony/http-client` (if not already in your dependencies)
2. `psr/http-client` is required by this bundle, but you can add it as root dependency
3. `composer require nyholm/psr7`
4. `composer require happyr/google-analytics-bundle`. Here my setup for the bundle
   ```yaml
   happyr_google_analytics:
       tracking_id: '%env(GOOGLE_ANALYTICS_TRACKING_ID)%'
       http_client: 'Psr\Http\Client\ClientInterface'
       http_message_factory: 'nyholm.psr7.psr17_factory'
   ```

Symfony autowiring is able to resolve `Psr\Http\Client\ClientInterface` because, in my case, there is only one implementation.

I also made it work with [HTTPlug Bundle](http://docs.php-http.org/en/latest/integrations/symfony-bundle.html#installation) by configuring a client and then use
```yaml
happyr_google_analytics:
    tracking_id: '%env(GOOGLE_ANALYTICS_TRACKING_ID)%'
    http_client: 'httplug.client.happyr_analytics'
    http_message_factory: 'nyholm.psr7.psr17_factory'
```

And `httplug.client.happyr_analytics` relies on
```yaml
httplug:
    # ...
    clients:
        # ...
        happyr_analytics:
            http_methods_client: true
```

I hope it will help
